# Generated by Django 4.2.5 on 2023-11-07 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='club',
            field=models.CharField(default='Nobody', max_length=50),
        ),
    ]
