# Generated by Django 4.2.4 on 2023-09-07 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('leaders', models.CharField(max_length=50)),
                ('emails', models.EmailField(max_length=254)),
                ('description', models.CharField(max_length=250)),
            ],
        ),
    ]
