# Generated by Django 4.2.5 on 2023-10-04 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='sheet_link',
            field=models.CharField(default='google.com', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='club',
            name='description',
            field=models.CharField(max_length=1000),
        ),
    ]
