# Generated by Django 4.2.5 on 2023-10-23 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0002_club_sheet_link_alter_club_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='sheet_link',
            field=models.CharField(max_length=150),
        ),
    ]
