# Generated by Django 4.2.5 on 2023-10-25 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0003_alter_club_sheet_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
